-- Add system_generated column to tool_comments table
ALTER TABLE tool_comments ADD COLUMN system_generated BOOLEAN NOT NULL DEFAULT FALSE;

-- Create index for filtering system vs user comments
CREATE INDEX idx_tool_comments_system_generated ON tool_comments(system_generated);

-- Add comment for documentation
COMMENT ON COLUMN tool_comments.system_generated IS 'Indicates if this comment was generated by the system (e.g., from Excel uploads) rather than manually by a user';