CREATE TABLE IF NOT EXISTS tool_checklist_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tool_type VARCHAR(255) UNIQUE NOT NULL,
    items_json TEXT NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_tool_checklist_templates_type ON tool_checklist_templates(tool_type);

